### ISSUE TITLE
Request to add a license to the repositories

### ISSUE THREAD

**Issue by pepe82sh** [toniebox-reverse-engineering/teddycloud#107]
Hi,
and thanks for the awesome work you guys did and are doing with opening this box! I'm in the process of creating a FreeBSD port of toniecloud. First just for my own entertainment (and to not have to run linux in a VM to run Docker on Linux to run teddycloud on docker), but I think if this feels proper and mature I'd like to commit it to the ports repo.
A port is basically a Makefile wrapping your make environment and applying patches or tweaks to successfully compile on FreeBSD.
Since that also includes downloading your release, maybe even modifying it, and then maybe redistributing it via prebuilt packages, licensing starts playing a role. Right now there is no license set in the project (as far as I can tell). This means all rights are reserved unless specifically granted from your side. (see ["Choosing the right License"](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)

Are you willing to put the project under a specific license, or If not, to grant modification and redistribution rights for the specific case?

Thanks again and talk soon :)

**Comment by SciLor** [comment]
Hey there,
As the lib cyclone is using GPLv2 with the "or-later" option. So we will do the same. Just work with it as it would already be GPLv2 or later.

I am curious to see what you will be doing =) and be glad to integrate it into our repo, as soon as you think it is mature enough.

**Comment by pepe82sh** [comment]
Thanks for the quick reply :) The funny thing is, that what I'm doing will basically be part of the FreeBSD ports repo and be a wrapper around your build scripts. Have only been a user of the ports collection so far, not an author, but the process is relatively straight forward. It even has a process to patch things prior to build, so I can fix things or make them "more Unixy" to comply with the intended paths. Already have it compiling (with one patch in cyclone. Sent them a PR). Now I need to change the paths for config and things and add a proper rc script. I'm not sure if you want those in your repo though.
The one thing I saw is that there is a proposal for configurable paths already. Having something like that either at compile time or at runtime or even both would be awesome. I think I'll patch in different paths right now, and if I have it running I'll maybe try and work on the existing ticket here to reduce the patchwork on my end.
I'll close this as my initial request has been resolved :)

**Comment by SciLor** [comment]
I think it makes sense to support a different path for the configuration file with some fallback to the current state. Feel free to make proposals to this to the issue. I just added a rough idea to it. You may be more savvy with the unix way.
[Change config path).](https://github.com/toniebox-reverse-engineering/teddycloud/issues/33)

**Comment by SciLor** [comment]
We already patched some cyclone files on our end by copying and modifying it. It is a bad way, but works. Maybe there is a nicer way to do that.

**Comment by SciLor** [comment]
We tried to reduce the external dependencies, so we are not limited by the environment and can run on our own + easy porting. We also had the idea to port teddyCloud to the ESP32.
Another thing is the TLS/SSL part. The CC3200 uses some legacy crypto we need to support, which doesn't work out of the box on most linux systems.

**Comment by pepe82sh** [comment]
Aah good to know! Kept it like that anyway, but now there is a good reason not to touch it in the future.
