### ISSUE TITLE
Function "Assign Unknown" cannot find selected content

### ISSUE THREAD

**Issue by oliver-koch** [toniebox-reverse-engineering/teddycloud#110]
### Function "Assign Unknown" cannot find selected content
_Tested on TeddyCloud v0.3.4 (79945c2) - 2024-01-06 10:25:32 +0000 linux-x86_64_

**What was tested:**
1. Goto TeddyCloud and select a content folder (e.g. 39578119) or the TAF file inside the content folder
2. Press button "Assign Unknown"
3. Put an unknown tag to the Toniebox
4. Toniebox responds with codeword "Murmeltier"

Attached you can find the logs:
```
INFO |handler_api.c:0138:handleApiAssignUnknown| got path '/39578119//500304E0'
INFO |handler_api.c:0148:handleApiAssignUnknown| Set '/teddycloud/data/content/default/39578119/500304E0' for next unknown request
INFO |handler_api.c:0094:queryPrepare| requested index for 'content'
WARN |contentJson.c:0275:content_json_update_model| Audio-id 6377A621 unknown but previous content known by model 10000908.
INFO |handler_cloud.c:0038:handleCloudTime|  >> respond with current time
INFO |mqtt.c:0684:mqtt_init_box| Skipping client 'Toniebox' (cn: 'default')
INFO |server.c:0570:server_init| 2 open HTTPS connections
INFO |server.c:0570:server_init| 3 open HTTPS connections
INFO |server.c:0248:httpServerRequestCallback| UA=toniebox-esp32-eu/v5.230.0, ESPFW=eu/v5.230.0
INFO |handler_cloud.c:0303:handleCloudContent|  >> client requested content for rUID 58899c12500304e0, auth 00000000...
INFO |handler_cloud.c:0329:handleCloudContent|  >> this is a unknown tonie, assigning '/teddycloud/data/content/default/39578119'
ERROR|handler_cloud.c:0355:handleCloudContent| Path to assign not available: /teddycloud/data/content/default/39578119
INFO |handler_cloud.c:0463:handleCloudContent| Content marked as no cloud and no content locally available
```

As far as i can understand it, the correct TAF was marked for the next unknown request. I can copy the folder path an enter it inside the teddycloud container
```
root@teddycloud:/# cd /teddycloud/data/content/default/39578119
root@teddycloud:/teddycloud/data/content/default/39578119# ll
total 30884
drwxr-xr-x 1 root root        42 Jan 17 11:07 ./
drwxr-xr-x 1 root root       560 Jan 19 08:09 ../
-rwxr-xr-x 1 1027 users 31620135 Feb 17  1980 500304E0*
-rwxr-xr-x 1 root root       197 Jan 16 12:11 500304E0.json*
```
Then a unknown tag is correctly detected. when it tries to "link" it to the previous selected content, it fails with the error
`Path to assign not available: /teddycloud/data/content/default/39578119`.
Folder path is correct, and cann be accessed on teddycloud.

**Comment by SciLor** [comment]
The log looks like teddyCloud is removing the filename somewhere between the assign unknown and the access of the box.

**Comment by SciLor** [comment]
It seems to be a more complex problem with the "overlay" within the configuration. The webinterface sets the internal.assign_unknown in the global fallback configuration with the id 0.
The box gets the a different configuration, lets say id 1 when it tries to access the assign_unknown variable.

The incomplete path your have seems to be another problem around that.

**Comment by SciLor** [comment]
[fix assign_unknown (workaround)](https://github.com/toniebox-reverse-engineering/teddycloud/commit/7d5d156222cd69fa5289fb32f31956e10ce960a7)
Fixed and available in the develop tag in several minutes.

**Comment by oliver-koch** [comment]
Retest OK with version from last development branch: TeddyCloud vX.X.X (7d5d156) - 2024-01-19 13:35:19 +0000 linux-x86_64

"Assign Unknown" did work. Thank you!

```
INFO |handler_cloud.c:0149:checkCustomTonie| Found possible custom tonie by password
INFO |handler_cloud.c:0310:handleCloudContent|  >> custom tonie detected, nothing forwarded
INFO |handler_cloud.c:0165:markCustomTonie| Marked custom tonie /etc/teddycloud/data/content/default/58899C12/500304E0
INFO |handler_cloud.c:0330:handleCloudContent|  >> this is a unknown tonie, assigning '/etc/teddycloud/data/content/default/1ACC2C15/500304E0'
WARN |contentJson.c:0275:content_json_update_model| Audio-id 60A61929 unknown but previous content known by model 10000209.
```
