### ISSUE TITLE
Please set a proper license

### ISSUE THREAD

**Issue by Schievel1** [toniebox-reverse-engineering/teddycloud#116]
From what I can tell this is GPL-2+, but if so it would help in packaging when you also set that in a license file in the repos root

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/teddycloud/issues/107

**Comment by SciLor** [comment]
Yes forgot it. Going to do that in the future

**Comment by Schievel1** [comment]
Sorry, apparently I did search wrong.
