### ISSUE TITLE
Support of several Flex-Tonies

### ISSUE THREAD

**Issue by oliver-koch** [toniebox-reverse-engineering/teddycloud#126]
### Enhancement:  Support of several Flex-Tonies

It would be very nice and comfortable to have more then one Flex-Tonie.
I suggest a comma separated list of Flex-Tonie UIDs.

**Comment by SciLor** [comment]
I think with the new /web interface and the convenient way to change content this is not needed anymore.

**Comment by moviebrain** [comment]
I understand this has been closed. Flex-tonies are tags that connect to whatever audio is playing in the web interface yes?

if I have two kids, two boxes, and they both want to listen to the same thing on headphones (which is not a hypothetical situation in my house) then having this synced single audio source sent to more than one box would be a welcome addition. I understand it could be low priority, but as a someday enhancement I would welcome it

**Comment by SciLor** [comment]
You can select the same TAF via the new /web interface.
In the future we will have TAPs that are playlists of audio files that can be set for a tag. This was you may edit multiple tags at once.
