### ISSUE TITLE
Change internal representation of UID

### ISSUE THREAD

**Issue by pepe82sh** [toniebox-reverse-engineering/teddycloud#127]
This is just a first glance thing looking at the code, so I might be totally wrong here.

To me it seems that UID is uint64 really, and the difference between UID and rUID is really just the byte order (little endian vs big endian). This wouldn't be very surprising as big endian is "network byte order", and most systems work with little endian internally.

Converting to a uint64 representation as soon as possible would (in the code) solve issues with string copies and comparisons, upper case vs lower case wouldn't be an issue anymore, and the problem of rUID vs UID would just need distinction when reading from string.

I'd be happy to give it a shot in 2 weeks or so, but I wonder if this has good reasons that I simply don't know of.

**Comment by g3gg0** [comment]
i can understand your impression. it might be right, maybe not. not sure.

We have the UID in different representation to be handled. As UID-string, as rUID-string as rUID bytes.
Quite a mix depending on what it's used for. That is also a bit pain for me.

And yeah, maybe uint64 might be the best choice plus some conversion routines back and forth.
If you could go through the code and check if it in the end gives cleaner code, it would be fine for me.

**Comment by SciLor** [comment]
Both representations are used for different purposes, the one to compare and the one to identify physical files.
But I see no problem streamlining it into a a UID uint64 representation, as this could clean up the code a bit.

I currently don't see that this would fix the lower/uppercase problem, we check for path existence for an UID, not checking each file/dir.

**Comment by pepe82sh** [comment]
The idea was that if you compare uint64 rather than strings you have no case anymore. But that might be easier said than done. Just looked at some code in handler_cloud.c and it seemed more complicated that it'd need to be. As stated previously, I'm not that deep into the code base and it might be a "Schnapsidee". I'll give it a try once I have some time.
