### ISSUE TITLE
Docs: Explain the purpose and usage of Flex Tonies

### ISSUE THREAD

**Issue by monsdar** [toniebox-reverse-engineering/teddycloud#129]
In teddycloud there is a setting regarding FlexTonies. However there is no real explanation what this is and why a user would use it. I could find a few traces in the forum and Telegram group, but not enough to connect the dots.

Would be cool if we could extend the wiki to give a general overview about the feature, why and how someone would use it.

**Comment by monsdar** [comment]
Perhaps later on this should be integrated into the web ui itself.

**Comment by g3gg0** [comment]
you are right. there is only that popup:
![grafik](https://github.com/toniebox-reverse-engineering/teddycloud/assets/479231/09bf31c2-1f57-4f2a-a647-62572b2f45d1)

**Comment by KaaNee** [comment]
Hey [@oliver-koch](https://github.com/oliver-koch), as you asking for multiple Flex Tonie-IDs on #126 you could explain the usage of it in a good way, maybe ? This would help many other users.

**Comment by henryk86** [comment]
Flex Tonie might be obsolet because of the new gui. Flex Tonie is a relict of the past ;)
Recommend: "Won't Fix" and Close

**Comment by monsdar** [comment]
Guess you are right
