### ISSUE TITLE
Streaming Spotify playlist

### ISSUE THREAD

**Issue by FinkeFlo** [toniebox-reverse-engineering/teddycloud#137]
As discussed in [RevvoX forum](https://forum.revvox.de/t/streaming-spotify/143) it would be nice to add Spotify streaming support.

**Comment by SciLor** [comment]
Duplicate of https://github.com/toniebox-reverse-engineering/teddycloud/issues/125

**Comment by zakx** [comment]
If anyone is looking for a solution, I have built a [Spotify Connect sink that can plug into Teddycloud](https://github.com/zakx/teddify).
