### ISSUE TITLE
Add Nick name in the content area

### ISSUE THREAD

**Issue by xsnoopy** [toniebox-reverse-engineering/teddycloud#140]
I think it would be great if on Teddycloud a written nick name for the tonies could be displayed in the content area. The name could be stored in the .json file. Not quite sure if tonie_model is not already used for that. 

This would make it easier if you want to replace content of a tonies. It gets confusing if you have a lot of tonies and just have the rUID.

Please see attached pictures, I am talking about the orange words. 

![example](https://github.com/toniebox-reverse-engineering/teddycloud/assets/63822202/0e89c3ce-2bc2-4d97-97ab-a1fab5c6b364)

**Comment by SciLor** [comment]
The overview will take the selected model of the content json in the directory, if this is set. So this feature won't be added.
Also with the v0.4.0 there is a first attempt to add a working prototype of the webgui under /web
