### ISSUE TITLE
Container Crashes

### ISSUE THREAD

**Issue by DavMem** [toniebox-reverse-engineering/teddycloud#143]
Hello,
 i am trying to get teddycloud running on homeassistant on an rpi4. When i boot up the container it always crashes with the following error. Am i missing something?

creating config dirs
creating /teddycloud symlinks
removed directory '/teddycloud/certs/server'
removed directory '/teddycloud/certs/client'
removed directory '/teddycloud/certs/'
'/teddycloud/certs' -> '/config/certs'
removed directory '/teddycloud/config/'
'/teddycloud/config' -> '/config/config'
removed directory '/teddycloud/data/content/default'
removed directory '/teddycloud/data/content/'
'/teddycloud/data/content' -> '/config/data/content'
removed directory '/teddycloud/data/library/'
'/teddycloud/data/library' -> '/config/data/library'
removed directory '/teddycloud/data/firmware/'
'/teddycloud/data/firmware' -> '/config/data/firmware'
TeddyCloud vX.X.X (-dirty) - 2024-03-26 20:29:17 +0000 linux-aarch64

INFO |settings.c:0691:settings_load_ovl| Load settings from /teddycloud/config/config.overlay.ini
INFO |settings.c:0691:settings_load_ovl| Load settings from /teddycloud/config/config.ini
ERROR|tls_adapter.c:0193:read_certificate| Failed to open '/teddycloud/certs/server/ca-root.pem' for cert type detection
ERROR|tls_adapter.c:0380:load_cert| Loading cert '/teddycloud/certs/server/ca-root.pem' failed
INFO |settings.c:1367:settings_load_certs_id| ********************************************
INFO |settings.c:1368:settings_load_certs_id|    No certificates found. Generating.
INFO |settings.c:1369:settings_load_certs_id|    This will take some time...
INFO |settings.c:1370:settings_load_certs_id| ********************************************
INFO |cert.c:0413:cert_generate_default| Generating CA certificate...
INFO |cert.c:0042:cert_generate_rsa| Generating RSA Key... (slow!)
cyclone/cyclone_crypto/cipher/aes.c:260:47: runtime error: left shift of 166 by 24 places cannot be represented in type 'int'
cyclone/cyclone_crypto/cipher/aes.c:268:55: runtime error: left shift of 217 by 24 places cannot be represented in type 'int'
cyclone/cyclone_crypto/cipher/aes.c:390:34: runtime error: left shift of 146 by 24 places cannot be represented in type 'int'
cyclone/cyclone_crypto/cipher/aes.c:400:34: runtime error: left shift of 201 by 24 places cannot be represented in type 'int'
cyclone/cyclone_crypto/cipher/aes.c:395:34: runtime error: left shift of 191 by 24 places cannot be represented in type 'int'
cyclone/cyclone_crypto/cipher/aes.c:385:34: runtime error: left shift of 206 by 24 places cannot be represented in type 'int'
/docker-entrypoint.sh: line 24:    25 Killed                  teddycloud

**Comment by SciLor** [comment]
This is a problem with your environment, maybe low memory
