### ISSUE TITLE
TC is using wrong folder during encoding the TAF file

### ISSUE THREAD

**Issue by Freneato** [toniebox-reverse-engineering/teddycloud#146]
When i use TAF encoding with teddycloud always the folder path
`/teddycloud/data/content/default/XXX` is used, also when i'm using the library path. 

New encoded TAF files should be stored in library to choose them easily for a tonie with new web-interface.

If i create a new folder in library `/teddycloud/data/library/content/default` and change to the folder to upload mp3s to convert them to TAF.
 Teddycloud is searching for the files in `/teddycloud/data/content/default/` -> this gives always an error in logfile:

`docker 1a257f27fe48[191]: ERROR|handler_api.c:1709:handleApiPcmUpload| invalid path: '/0XX - Hanni und Nanni/' -> '/teddycloud/data/content/default/0XX - Hanni und Nanni/'`

Workaround: Create the TAF file in content folder and move the file afterwards manually to library

**Comment by SciLor** [comment]
Commit https://github.com/toniebox-reverse-engineering/teddycloud/commit/cf51c89e13540792436185b334f772843f5e5a40 should fix that =)

**Comment by Freneato** [comment]
yupp - fixed for me 👍
