### ISSUE TITLE
Hang at Patching flash image…

### ISSUE THREAD

**Issue by moviebrain** [toniebox-reverse-engineering/teddycloud#152]
This is a help/clarification request

I have the docker version of teddycloud running, I have extracted firmware from two boxes both legacy and web serial ways. 

When attempting to patch the firmware the cloud version hangs without progress or error codes at “Patching flash image…” and doesn’t progress to showing the red Flash ESP button, I’m unsure what’s happening. This was the help part of my issue: what can I try to resolve or investigate, is there a specific log I should be checking. if so can it be added to the page as a scrolling log or progress indicator?

![IMG_6309](https://github.com/toniebox-reverse-engineering/teddycloud/assets/52259292/248dc8ab-aca1-453a-98a6-8fe05792c3d3)

Clarification request: when using the cloud ESP READ function, and patching, does the cloud version save the unmodified firmware somewhere automatically
 if I’d like to revert? The wiki doesn’t specify, and the legacy instructions makes it a manual step.

**Comment by moviebrain** [comment]
Apologies, but I’m not getting an email confirmation email at the forum site. I am having the same issue as
  https://forum.revvox.de/t/segv-when-patching-esp32-with-web-ui/404
  
Raspberry pi 5, bookworm, teddycloud 0.4.3. I have never gotten past the Patching step. I have stopped the docker container, removed images and volumes, and started it fresh from the example docker-compose.yaml. I freshly read the esp successfully, but on Patching the server restarts and I see the following in the docker log. 

![IMG_6317](https://github.com/toniebox-reverse-engineering/teddycloud/assets/52259292/f472e6dc-84c6-48b9-b50b-d0f1e07f67ce)

**Comment by SciLor** [comment]
Could you please open the Network tab in Chrome Dev Console and share the details of the call to the API?

The error occurs in this line:
[char *patched_path = custom_asprintf("%s%spatched_%s.bin", rootPath, PATH_SEPARATOR, mac);](https://github.com/toniebox-reverse-engineering/teddycloud/blob/82e20b3acb3f1818d697af00022b10468a05deca/src/handler_api.c#L1142)
it seems so, that the mac is NULL.

The firmware is dumped to the /firmware volume within teddyCloud. So could you peek within the file if it looks ok or is full off 0x00?

PS: Regarding your mail, you had a typo and your mail ended with ".con", I just fixed that for you.

**Comment by moviebrain** [comment]
> Could you please open the Network tab in Chrome Dev Console and share the details of the call to the API?
> 
> The error occurs in this line: [char *patched_path = custom_asprintf("%s%spatched_%s.bin", rootPath, PATH_SEPARATOR, mac);](https://github.com/toniebox-reverse-engineering/teddycloud/blob/82e20b3acb3f1818d697af00022b10468a05deca/src/handler_api.c#L1142) it seems so, that the mac is NULL.
> 
> The firmware is dumped to the /firmware volume within teddyCloud. So could you peek within the file if it looks ok or is full off 0x00?
> 
> PS: Regarding your mail, you had a typo and your mail ended with ".con", I just fixed that for you.

![2024-04-03 22_09_39-TeddyCloud administration interface](https://github.com/toniebox-reverse-engineering/teddycloud/assets/52259292/2fa4f153-1e36-46e9-b6f7-6aa098386056)

![2024-04-03 22_23_38-binvis io - ESP32_4827e2682f3c_2 bin — Mozilla Firefox](https://github.com/toniebox-reverse-engineering/teddycloud/assets/52259292/1a83fa07-5d95-448d-b493-e718eb66b6fd)

Here is the captured API call, it is not NULL. Here is a screenshot of the bin that failed most recently in that API capture, it is not empty that I can tell. Please let me know if there is anything else I can provide.

**Comment by SciLor** [comment]
Fixed in develop, will be fixed in v0.4.4 or use the develop tag in docker

https://github.com/toniebox-reverse-engineering/teddycloud/commit/98fda205c4326c8a406ff787025cc452b6a81cd2

**Comment by moviebrain** [comment]
> Fixed in develop, will be fixed in v0.4.4 or use the develop tag in docker
> 
> [98fda20](https://github.com/toniebox-reverse-engineering/teddycloud/commit/98fda205c4326c8a406ff787025cc452b6a81cd2)

I’m very bad at C, but I’d like to understand. The error in code was because the function used to parse the file name was storing the separators (underscores) as a char array and not a single character? Or was it the underscores added for writing out duplicate file names when I read the flash multiple times? Because it also failed on the initial non-appended-duplicate-file version.

I’m just curious is all, thanks for the fix and your time.

**Comment by SciLor** [comment]
I used a %s instead of a %c for reading a char. This means it will try to read the memory address starting on the separator until it finds a null byte as string ending, instead of just reading a single character.

**Comment by moviebrain** [comment]
Got it, thanks. I’ll test soon and close assuming the fix gets me further.

**Comment by moviebrain** [comment]
Closed, fixed in develop as you say.

**Comment by SciLor** [comment]
I keep it open until the next release for others sharing the same issue.
