### ISSUE TITLE
react-dom.development.js can't be loaded. Old UI fails loading

### ISSUE THREAD

**Issue by CTeipen** [toniebox-reverse-engineering/teddycloud#153]
![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/8715591/180829f7-fd2f-4c61-8a50-87f8ab87a8e3)

React DOM CDN isn’t reachable. Old TeddyCloud UI does not load.

I read that this source isn't supported in the near future. Maybe it should be cached on a server or stored in the sources of TeddyCloud. Just some thoughts of mine.

**Comment by CTeipen** [comment]
https://react.dev/reference/react-dom#resource-preloading-apis

Here is a mentioning of the deprecation. I'm not sure of those listed are related to the ones being used by TeddyCloud.

**Comment by SciLor** [comment]
We need a copy of 

    <script src="https://unpkg.com/react@16/umd/react.development.js"
        integrity="sha512-LVEAOXGRRqHiT+4awmHwL5emvXg+BTr8cC/eDF0pLuwEySgG55Pt2gfN2X6BenCsocmb2kKJ7QJVppWftFpcoA=="
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"
        integrity="sha512-MizB1VlWh4kvP5l+aBc2umqPc3V2bApU+SSqi70PZbhkLTXtJuIHXEY2LDkwqyX5yh+IzqTCP0Y0yI698i8oTA=="
        crossorigin="anonymous"></script>

to integrate it directly into teddyCloud

**Comment by CTeipen** [comment]
[Uploading react-dom.development.js.txt…]()

**Comment by Kuchen404** [comment]
[react-dom.development.zip](https://github.com/toniebox-reverse-engineering/teddycloud/files/14955229/react-dom.development.zip)

This is what my Browser had cached. I hope this helps

**Comment by CTeipen** [comment]
[react.development.js.txt](https://github.com/toniebox-reverse-engineering/teddycloud/files/14955241/react.development.js.txt)

**Comment by CTeipen** [comment]
i put the files in the library folder of the www folder. With the lines below it works again. 
`<script src="library/react.development.js"></script>
<script src="library/react-dom.development.js"></script>`

The console logs a warning about the deprecate state of ReactDOM.render
"react-dom.development.js:73 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot"

**Comment by SciLor** [comment]
Thank you for your support.
I added the libs directly to teddyCloud and it is working again in the develop tag.
