### ISSUE TITLE
Update from 0.34 -> 0.44: WARN |server_helpers.c:0792:httpServerUriNotFoundCallback|  >> 404 index.shtm

### ISSUE THREAD

**Issue by mptr8956** [toniebox-reverse-engineering/teddycloud#155]
Tried to update from 0.34 to .44 today, now i cant access the webinterface anymore. log says:
WARN |server_helpers.c:0792:httpServerUriNotFoundCallback|  >> 404 index.shtm

![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/73469840/fe859d48-75b4-418d-a22c-621f5e59468b)

**Comment by mptr8956** [comment]
nvm, deleted the old config.ini, restarted the container, now it works again!

**Comment by jevellangelo** [comment]
I'm running v0.5.2 and getting the same 404 error. I tried OP's fix but that didn't work for me. I've opened both port 80 and 443 using the docker compose file. Here is the log 
```
2024-07-31 15:57:29 teddycloud  | WARN |tls_server_fsm.c:0260:tlsPerformServerHandshake| TLS handshake failure!
2024-07-31 15:57:29 teddycloud  | WARN |server_helpers.c:0792:httpServerUriNotFoundCallback|  >> 404 index.shtm
2024-07-31 15:57:29 teddycloud  | INFO |server.c:0673:server_init| 1 open HTTPS connections
```

**Comment by henryk86** [comment]
Https is disabled by default since 0.4.4 or so. Use http to access the webfrontend.

**Comment by jevellangelo** [comment]
Thanks for pointing me in the right direction! Just getting started with teddycloud. 
I was able to edit the correct line in the config.ini file.
