### ISSUE TITLE
Assign image to custom tag like assigning Tonie model

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud#156]
Currently you can assign a tonie model to your custom tag. After that, the custom tag looks like the tonie in the web gui.

I would love to have the option to enter a image url (or in a deluxe version add an image) which then creates/adapts the entry in the tonies.custom.json and displays the image instead of the question mark icon in the web gui.

how it could be:

<img width="319" alt="image" src="https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/a3ba5125-51e4-4bdf-ae18-d3c4df3d1109">
Additional line After Model: Image (edit:Icon)

And then a dialog selecting a picture (or just pasting a url).

**Comment by SciLor** [comment]
I think it makes sense to implement a full editor for the tonies.custom.json entries.

**Comment by henryk86** [comment]
This needs actions in both Frontend and backend I assume. Frontend provide the form and backend provide the api for adding an entry to the custom.json?

**Comment by Exitras** [comment]
I also would love to add custom images. Please implement this into the Teddycloud 😊

**Comment by henryk86** [comment]
@Exitras just for information. You can already assign custom images through the tonies.custom.json. But the images needs to be hosted somewhere as they can only be linked as url.

**Comment by Exitras** [comment]
@henryk86, thanks a lot for this information! Do you have an instruction/guide for this? Where do I have to put the link?

**Comment by henryk86** [comment]
Have a look here: https://tonies-wiki.revvox.de/docs/tools/teddycloud/tonies-custom-json/

**Comment by Exitras** [comment]
Ahh, that worked very well. Thanks a lot! It's much nicer with my images :)

**Comment by henryk86** [comment]
it's part of https://github.com/toniebox-reverse-engineering/teddycloud/issues/176
