### ISSUE TITLE
Change GUI to http prevents WebSerial usage

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud#158]
The change to expose the frontend only to http (by default, but https can be enabled) prevents the direct use of the webserial feature to read, patch and write firmware to esp32.

<img width="826" alt="image" src="https://github.com/toniebox-reverse-engineering/teddycloud/assets/166761451/ff43be0d-0b35-4be5-9be5-2ab0ad032ab8">

Maybe this must be separated from the frontend and moved to a kind of api where the backend does the action and frontend just requests that from the backend. But I am not aware how it works currently.

**Comment by SciLor** [comment]
We are working on authentication for the frontend.
It may make sense to add a short notice to the flashing section to temporarily enable https access and add a general warning if the https port is exposed.

**Comment by henryk86** [comment]
Is it necessary to have the webserial in the frontend? If I am wrong if I think if the whole webserial stuff is moved to backend and then it is still possible to do so even if the frontend is only http?

**Comment by SciLor** [comment]
It is possible to enable it when needed
