### ISSUE TITLE
Tonie pictures have different size in new web interface /web

### ISSUE THREAD

**Issue by Freneato** [toniebox-reverse-engineering/teddycloud#162]
every picture which is used for displaying the tonie figure should be shown in the same size to get the same appearance.

![tonie_pic_size](https://github.com/toniebox-reverse-engineering/teddycloud/assets/28085427/4e54cb7f-51c9-4b77-a47d-a6931bb017d9)

**Comment by henryk86** [comment]
This CSS fix the problem... will try to get it into the antd card design. or inject css directly... but later...

`.ant-list .ant-row > div,
.ant-list .ant-row .ant-col:first-child {
  display: flex;
}
.ant-list .ant-row .ant-list-item {
  flex: 1 1 auto;
}
.ant-list .ant-row .ant-list-item .ant-card {
  height: 100%;
  display: flex;
  flex-direction: column;
}

.ant-card-cover {
    height: 100%;
    align-content: center;
}`

**Comment by henryk86** [comment]
https://github.com/toniebox-reverse-engineering/teddycloud_web/pull/19 committed here. in a first version using app.css file...

**Comment by henryk86** [comment]
(the image size is unchanged, but the card is adapted)

**Comment by henryk86** [comment]
the images varies besides the size also regards to the "padding" around the image. so a resizing of the image would be still no satisfiing solution i would say.
