### ISSUE TITLE
Webinterface https not reachable - get 401

### ISSUE THREAD

**Issue by fila612** [toniebox-reverse-engineering/teddycloud#185]
with [TeddyCloud vX.X.X (c5803f1) - 2024-06-02 21:05:52 +0000 ubuntu linux-x86_64(64)](https://github.com/toniebox-reverse-engineering/teddycloud/releases/) it seems that the http-only switch is not working.
Switch is set off but the web interface is only reachable via http, with https I get an 401.

**Comment by henryk86** [comment]
Please disable the auth cert option. Or use the box certs to access

**Comment by henryk86** [comment]
More Details: https://github.com/toniebox-reverse-engineering/teddycloud/issues/183

**Comment by fila612** [comment]
thanks for helping, issue closed.
Solution: disabling "HTTPS client cert auth":
![Bildschirmfoto 2024-06-08 um 16 44 04](https://github.com/toniebox-reverse-engineering/teddycloud/assets/29542374/a12ed339-9c43-4fbb-90d3-c703494af4ee)
