### ISSUE TITLE
Provide timestamps for taf file (track)

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud#187]
In the header of a taf file is (if available) a array stored with the pagesegements when a new track starts. The audioplayer in the new frontend needs timestamps (in seconds) to be able to jump between the tracks.

As far as I know there is no way to calculate the seconds from the segmentnumbers. You need the whole taf file to extract that information.

so it would be great to be able to use the track skipping feature of the webplayer to get an array with the starting times of each track. To be usable within tonies overview and content/library browser view, only the filename (+path) should be passed.

**Comment by SciLor** [comment]
You can calculate the position in the file with the track information:
4096 + num*4096

Then extract the position from the OggS header.

![image](https://github.com/user-attachments/assets/e9115b3c-dacb-4f22-a9f7-524a2d841ca4)
