### ISSUE TITLE
Home Assistant Mqtt Auto discovery 

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud#19]
https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery

**Comment by g3gg0** [comment]
https://github.com/g3gg0/ESP32_VuePower/blob/master/src/HA.ino
my own Home Assistant connector

**Comment by g3gg0** [comment]
https://github.com/g3gg0/ESP32_VuePower/blob/master/src/MQTT.ino
MQTT interface (using arduino lib) and how to use the HA calls

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/teddycloud/commit/6be01f1116a9f7038549b888bd6289234389ccb2
