### ISSUE TITLE
Reading flash from ESP fails at 99.99%

### ISSUE THREAD

**Issue by BananenTraeumer** [toniebox-reverse-engineering/teddycloud#195]
Hi,
when trying to read the flash from my ESP32 toniebox using the teddy cloud web interface I keep getting a timeout error at 99.99%.
Have tried it multiple times in different browsers (Edge 126.0.2592.87 & Chrome 126.0.6478.127) on macOS all with the same error.
<img width="1440" alt="read-flash-timeout" src="https://github.com/toniebox-reverse-engineering/teddycloud/assets/174967346/051c864e-0cef-439f-b4ee-8380eaea692c">

Any idea how to fix this? I have no experience using the esptool directly on my local machine. Do you have any documentation which commands to use for reading and updating the flash with the new certificates?

**Comment by SciLor** [comment]
You can use the legacy way which is also described in the wiki if you have trouble using the browser for the steps.
