### ISSUE TITLE
cant migrate TAF Files with AudioID "1"

### ISSUE THREAD

**Issue by bluenazgul** [toniebox-reverse-engineering/teddycloud#196]
TAF Files with AudioID "1" (empty Creative Tonies) can not get migrated form Content to Library

the issue could be located in `handler.c —> moveTAF2Lib`

`if (audioId <= 1)
            {
                TRACE_WARNING(">> Audio ID is %" PRIu32 ", not moving to library\r\n", audioId);
                error = ERROR_INVALID_FILE;
            }`

thanks to @henryk86 for the find

**Comment by SciLor** [comment]
This is intended, as there can be different TAFs with the same audio id 1
