### ISSUE TITLE
Managing taf files by AudioID

### ISSUE THREAD

**Issue by kreativmonkey** [toniebox-reverse-engineering/teddycloud#198]
It would be nice to manage/edit the taf files by Audio ID (and custom ones too). Renaming the taf file to a human readable name to get a easy overview off the content. That also will make it more easy to remap audio files to custom tags or stick cloud content to the custom tags. Ideal will be the library page to edit the content. This can be another enhancement to the Issue #188

**Comment by henryk86** [comment]
so new features like: 
* Rename file
* Move file
Therefore 1 or 2 new API endpoints are needed.

**Comment by SciLor** [comment]
/api/fileMove
paramters: source, target

**Comment by henryk86** [comment]
@kreativmonkey in current develop is the new api integrated. feel free to play with the rename and move functionality and test it also.
