### ISSUE TITLE
Permanent download the Images and do not  link to tonies website

### ISSUE THREAD

**Issue by Mannshoch** [toniebox-reverse-engineering/teddycloud#200]
Currently, If you setup the Toni and Tonibox. The Images for them are linked Online.

Please download the images and store them localy

**Comment by g3gg0** [comment]
Solid idea, but could you clarify the legal side of things? How does "fair use" play out under EU and specifically German law?
I’m guessing their image rights could leave us open to a lawsuit.

**Comment by Mannshoch** [comment]
good Question. 
But as far I know. It should not be a problem If you are using it for private and not to make money with it.
As far I am uncertain if you are allowed to ship these images with your project. 
But you are allowed to give a download-to-cache setting and let me download it, so I could get a private Copy by clicking on something. 

So I would change it that way that on first use of these images you could ask if teddycloud should download and store data locally. And may allow to do it again to refresh if a new product is released.

**Comment by SciLor** [comment]
We are not allowed to copy and ship the image files, as this is not our property. This would bring us in trouble.
Caching it in teddyCloud itself may be helpful long term. But this is something with low priority.

**Comment by g3gg0** [comment]
> good Question. But as far I know. It should not be a problem If you are using it for private and not to make money with it. As far I am uncertain if you are allowed to ship these images with your project. 

EU laws are continuously aligning more with the american concept of "fair use". 
Without this exact term and not with just a single paragraph, however.
From a high-level perspective, for personal or academic use, you can generally download and use the images.

However, as an open-source project, we would be individuals sharing these images with strangers on the internet, not just friends or family. In this context, what you'd typically call "fair use" doesn’t apply.

**Comment by g3gg0** [comment]
with the latest version a simple caching features is implemented.
image links from the json won't be just forwarded anymore, but hashed and provided via /cache/ path in teddycloud.
depending on the settings, the images get downloaded either on first access or all at once during startup.
