### ISSUE TITLE
how to delete of "old" Tonies?

### ISSUE THREAD

**Issue by fila612** [toniebox-reverse-engineering/teddycloud#204]
Hi, 

I have some old Tonies which are not longer in usage and in our household. I would like to delete them, but they are displayed again and the folders and json files are also created.
Is this a feature or a bug?
The timestamp may be conspicuous here, as it is identical for these.
The following tonies have already been deleted (in the web-ui and also in the file system):
![Bildschirmfoto 2024-08-18 um 16 54 23](https://github.com/user-attachments/assets/dc60c37a-ab5a-4509-896b-93319c687a3a)

**Comment by SciLor** [comment]
The only way to remove them is to either deleting them manually on the box or hide them in the tonies overview (it is in the current develop version)
