### ISSUE TITLE
HowTo: Picture Path to use picture fro travel Tonie

### ISSUE THREAD

**Issue by fila612** [toniebox-reverse-engineering/teddycloud#206]
Hi,

I've put some content to my library and therefor I'd like to use a separate picture as it was described in this issue ([link](https://github.com/toniebox-reverse-engineering/teddycloud_web/issues/80)).

I've add this section into my tonies.custom.json:
        "no": "0",
        "model": "c-47110815",
        "language": "de-de",
        "category": "travel-tonie",
        "pic": "lib://pictures/traveltonie.png"

but I don't know which path I have to use to for traveltonie.png.
This png is stored at the library path .../pictures/traveltonie.png

**Comment by henryk86** [comment]
I had added a folder in the www directory where the unknown_img.png is placed.

e.g. folder custom_img

then you can link the image with the http://[url to teddycloud]/custom_img/image.png

but be aware, adding a folder in www can be creating a conflict in future if a folder is added in teddycloud with the same name.

**Comment by fila612** [comment]
thanks, that worked for me. had to add the www-folder to the shared docker volumes in portioner stack.

**Comment by SciLor** [comment]
> thanks, that worked for me. had to add the www-folder to the shared docker volumes in portioner stack.

Don't add the www folder! It will break upcoming updates. Use a custom subfolder!
