### ISSUE TITLE
Update of 500304E0 after a previously unknown tonie not working

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud#215]
If I place a new tonie whose content/audioId/hash is not yet in the tonies.json (or the whole entry), the file 500304E0 is created with model: "".

If the content/audioId/hash is added to the tonies.json, the file 500304E0 is not updated with the the actual model automatically. 

It shall only not be updated if a model was previosly set manually. 

More details of this bug can be found here:

https://forum.revvox.de/t/recreate-content-db/704/1

**Comment by SciLor** [comment]
I just fixed this with the commit
https://github.com/toniebox-reverse-engineering/teddycloud/commit/d8f051a6f14f012bb5df8809487b0d3f71fe0e32
