### ISSUE TITLE
Provide API to upload files to library

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud#216]
If you want to copy / upload files to your library, you need to do that currently using WinSCP or any other file transfer program.

It would be great if you could upload files using the webgui. Therefor an api is needed where you can pass a file (or multiple) and a targetpath.

**Comment by SciLor** [comment]
There already is an upload endpoint, see the legacy webgui.

**Comment by henryk86** [comment]
Ok, was not aware of that 🥸 will check it out
