### ISSUE TITLE
Audio Encoder improvements

### ISSUE THREAD

**Issue by fila612** [toniebox-reverse-engineering/teddycloud#223]
Hello,

I've some ideas/feature request around the audio encoder. based on my current use case to convert my audio disks to tonies.
The audio encoder could use the file name of the audio file as a default setting. furthermore, the path selection could be left active until the page is called up again. 

It would also be nice to insert a batch job, e.g. to generate 10 TAFS from 10 MP3s.

thanks

**Comment by henryk86** [comment]
Please one request per ticket. If this request is related to the gui... create the request in the teddycloud_web repository.

> The audio encoder could use the file name of the audio file as a default setting

Could be added if ONLY one file is added to the drag and drop field and name field is empty. **Will add that**

> furthermore, the path selection could be left active until the page is called up again.

Should be easily possible. **Will add that**

> It would also be nice to insert a batch job, e.g. to generate 10 TAFS from 10 MP3s.

Thats a taff thing. some want to combine 10 mp3s to one taf. That would be a complete new functionality. (Even i would love to ave something like that to define a couple of tafs, but then let the encoding happen in the background). Would extract that to an own request in teddycloud_web.
