### ISSUE TITLE
[CC3235] Docker container generated certificates not working

### ISSUE THREAD

**Issue by inonoob** [toniebox-reverse-engineering/teddycloud#230]
Hey all, 

I wanted to give a feedback concerning flashing the certificates for the Toniebox with the CC3235 chip. 

The Docker certification creation process seems not to work for Tonieboxes with the CC3235 chip. I did find some posts where I could find the solution.

[https://forum.revvox.de/t/cc3235-tls-alert/565](url)

### Problem: 
I followed the insturction for CC3235 by the letter. 
- I dumped my certificates from the toniebox. ==> Worked 
- I extracted them via CC3200tool ==> Worked 
- Create teddycloud via docker-composer on debian VM on proxmox => Worked 
- Waited for the certification to be created => worked 
- Restarted the docker container ! => worked
- Copied certificates from toniebox to teddy cloud 
- Compiled with CC3200 tool the new firmware including CA.der from teddycloud ==> Worked
- Flashed with flashrom on toniebox ==> Worked 
- Set DNS  "prod.de.tbs.toy" to teddy ip ==> Worked 
- Connection between Teddyclound and toniebox failed ! Certificate issue. 

### Solution

- Create certificate with the "old" gencert.sh and installed faketime [https://raw.githubusercontent.com/toniebox-reverse-engineering/teddycloud/master/contrib/gencerts.sh](url)
- Copied all certificates created in server folder to the server certificate folder of teddycloud. 
- Flashed CA.der generated by the old tool on the toniebox 
- Teddycloud and toniebox did see each other direclty. 

### Feedback

For toniebox with CC3235 you need to generate the certificates outsite the docker container and replace everything with the gencert tool created ones.

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/teddycloud/issues/138

Thank you, this is related to

**Comment by henryk86** [comment]
added this in the teddycloud guide:

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/0b9afad6-a060-4333-a4e9-6f20797145e3">

**Comment by inonoob** [comment]
Looks good !

**Comment by marco79cgn** [comment]
@inonoob You're right. I just set up teddycloud from scratch (using docker and the `latest` tag) and the automatically generated server `ca.der` is not even readable with openssl:

`openssl x509 -inform der -in ca.der -text`

Output:
```
unable to load certificate
548179536384:error:0D0E20DD:asn1 encoding routines:c2i_ibuf:illegal padding:../crypto/asn1/a_int.c:187:
548179536384:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=serialNumber, Type=X509_CINF
548179536384:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=cert_info, Type=X509
```

Whereas it works perfectly fine reading the generated `ca.der` from the `gencert.sh`: 

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7a:d7:95:**:**:**:**:**:**:**:**:**:**:**:**:**:**:ee:73:f4
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = DE, CN = Teddy CA
        Validity
            Not Before: Nov  2 23:00:00 2015 GMT
            Not After : Jun 23 23:00:00 2040 GMT
        Subject: C = DE, CN = Teddy CA
    ...
```

**Comment by brechsteiner** [comment]
I can confirm this behavior with version 0.6.4

**Comment by brechsteiner** [comment]
the problem is with the serial, but i don't know how to fix it.
