### ISSUE TITLE
suggestion: remove the file filter in tonies/tonie/edit model/source

### ISSUE THREAD

**Issue by Wyphorn** [toniebox-reverse-engineering/teddycloud#244]
It is possible to add all kind of files in library, also files without extension which keep the overview lean.
When try to assign a tonie to a library with edit the tonie model > source, there will be just .taf be visible to connect.
For me it would be nice to remove the file filter and allow every file from library to chose there.

**Comment by SciLor** [comment]
TAFs should have a TAF ending, as the library is used to store all sorts of files. Especially TAFs, TAPs and normal audio files.
Only TAPs and TAFs can be used as source for the tags.
Non experienced used otherwise will think, that they can assign MP3 or other audio files to the tags directly.
