### ISSUE TITLE
Add Navi blue colored Toniebox to tonieboxes.json

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud#247]
this one:

https://tonies.com/de-de/bundles/toniebox-sonderedition-navy-blau/

images:
https://images.cdn.europe-west1.gcp.commercetools.com/cffb5678-47af-495c-9f19-1c2ccfc5910c/BOX11001754_5_a-kXLCXBb4.png

**Comment by marco79cgn** [comment]
I have exactly this box. Don't really know how the cropping works or what's the target size.
```
{
    "id": "11001754",
    "name": "Navy Blue",
    "img_src": "https://cdn.tonies.de/thumbnails/Box_blau_limitedEdition_Cam02_uc_sRGB.png"
}
```

There is also a new creative tonie which comes bundled with this navy blue box. 
Kreativ-Tonie Superheld in der Sonderfarbe hellblau-gold
http://cdn.tonies.de/thumbnails/Tonie_limitedEdition_Standalone_uc_sRGB.png

Box with Tonie: 
https://images.cdn.europe-west1.gcp.commercetools.com/cffb5678-47af-495c-9f19-1c2ccfc5910c/BOX11001754_1_a-78sEYbTs.png

**Comment by henryk86** [comment]
{
        "id": "11001754",
        "name": "Navy Blue",
        "img_src": "https://images.cdn.europe-west1.gcp.commercetools.com/cffb5678-47af-495c-9f19-1c2ccfc5910c/BOX11001754_5_a-kXLCXBb4.png",
        "crop": [
            6,
            37,
            1.27
        ]
    },

thats the right entry (the image has the same view angle as the default boxes)

**Comment by marco79cgn** [comment]
@henryk86 
I always get this image/url which has a different viewing angle. 
https://cdn.tonies.de/thumbnails/Box_blau_limitedEdition_Cam02_uc_sRGB.png

<img width="352" alt="toniebox-navy" src="https://github.com/user-attachments/assets/ec17f551-fb7d-4672-8a24-ef4e3fe984c8">

<img width="410" alt="toniebox-navy-02" src="https://github.com/user-attachments/assets/f0ec2ac7-101a-4c9c-8761-50ea7b0d1ec9">

On my account overview, there is even a box with wrong aspect ratio. Maybe they don't have this angle by themselves.

<img width="358" alt="Bildschirmfoto 2024-11-10 um 11 18 58" src="https://github.com/user-attachments/assets/92d3109e-06b8-4113-87e7-853f32c4b89f">

When I set up my Toniebox for the very first time (before Teddycloud), I also sniffed the communication with Proxyman (mitmproxy alternative) and also there, I found the same picture.

```
{
  "data": {
    "households": [
      {
        "id": "8e******-****-****-****-******43",
        "name": "****",
        "ownerName": "Marco",
        "access": "owner",
        "tonieboxes": [
          {
            "accelerometerEnabled": true,
            "household": "8e******-****-****-****-******43",
            "householdId": "8e******-****-****-****-******43",
            "id": "********",
            "imageUrl": "https://cdn.tonies.de/thumbnails/Box_blau_limitedEdition_Cam02_uc_sRGB.png",
            "itemId": "11001754-51009520",
            "ledLevel": "on",
            "maxHeadphoneVolume": 100,
            "maxVolume": 100,
            "name": "Marcos Navybox",
            "tapDirection": "left",
            "timezone": null,
            "features": [],
            "settingsApplied": true,
            "onlineState": "unsupported",
            "battery": {
              "percent": null,
              "status": "unknown",
              "__typename": "TonieboxBattery"
            },
            "__typename": "TonieboxQuery"
          }
        ],
        "__typename": "HouseholdQuery"
      }
    ]
  }
}
```

Any other idea where I might get the correct image from?

**Comment by henryk86** [comment]
then we will use the other image for now
thanks for your search :)

**Comment by henryk86** [comment]
Just a reminder: right place for this is the tonieboxes.json in the tonies-json repository
