### ISSUE TITLE
MQTT connect doesn't work

### ISSUE THREAD

**Issue by mcr-ksh** [toniebox-reverse-engineering/teddycloud#248]
Hello,

I have a MQTT server configured:
<img width="458" alt="image" src="https://github.com/user-attachments/assets/37ff4cb3-93ef-4f77-9631-e2ad094a8adc">

The MQTT server that doesnt work:
`INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0313:mqttConnect| Connect to 'mqtt.local'
INFO |mqtt.c:0334:mqttConnect|   trying IP: 10.12.x.x
ERROR|mqtt.c:0341:mqttConnect| Failed to connect to MQTT: End of stream [512]
INFO |mqtt.c:0432:mqtt_thread| Too many errors, disabling MQTT
`

However, credentials are valid and topic subscription works verified using MQTT explorer. There is no encryption on 1883. mosquitto 1.6.9.
Whats wrong here?

**Comment by SciLor** [comment]
I see no password for your user here and what do the mosquitto logs say?

**Comment by mcr-ksh** [comment]
> I see no password for your user here and what do the mosquitto logs say?
That is just left free. All the info is there. The mosquitto log doesnt say anything. zero info.

Here from the TG:
![2024-11-10 12 16 50](https://github.com/user-attachments/assets/a7f8dbe7-9cf9-4555-bdb6-b63d711124ae)
![2024-11-10 12 16 45](https://github.com/user-attachments/assets/97f68937-267a-4a9b-9b02-263f14362e4b)
With raw packet dump. red is marked some conf. part of the topic and username/pw.

MQTT is private one. It works when connecting using MQTT Explorer. I tried from multiple devices but from the docker container it fails. It's already in PROD use for years. I also tried SSH tunnels right now and it works

This is from MQTT explorer client. The difference is the Topic prefix that also adds the "/status" to packet. While the working clients subscribe to the topic in the packet after the authentication

**Comment by SciLor** [comment]
Please try a user with a password.

**Comment by mcr-ksh** [comment]
I think I found the issue:
```
17│1731246952: Client <unknown> disconnected due to QoS too high or retain not supported. 
17│1731246953: New connection from 192.168.50.4:43934 on port 1883.
17│1731246953: Client <unknown> disconnected due to QoS too high or retain not supported.
17│1731246954: New connection from 192.168.50.4:43948 on port 1883
17│1731246954: Client <unknown> disconnected due to QoS too high or retain not supported.
```
mosquitto.conf
`#retain_available false
retain_available true`

Sould be nice not to be forced to retain the messages.

**Comment by SciLor** [comment]
Please create an issue for this feature request, so we don't forget it.
