### ISSUE TITLE
A fatal error occurred: Corrupt data, expected 0x1000 bytes but received 0xde2 bytes

### ISSUE THREAD

**Issue by bykof** [toniebox-reverse-engineering/teddycloud#266]
Hi folks, 
first, thank you very much for making this whole thing possible 🙏 
So I get this error, when I try to read the esp32 with esptool.py

The command I use: 
```
esptool.py -b 921600 read_flash 0x0 0x800000 tb.esp32.bin
``` 
The error I get:
```
A fatal error occurred: Corrupt data, expected 0x1000 bytes but received 0xde2 bytes
```

I got a brand new toniebox and I use the 4 Pin Programmer I2C Module Test Tool PCB Terminal 1*4P Gold Plated Pogo Pins from AZDelivery: https://www.az-delivery.de/en/products/4-pin-prototyping-clamps

And also the USB-C TTL Adapter from AZ Delivery: https://www.az-delivery.de/en/products/usb-c-zu-ttl-serial-adapter-fur-3-3v-und-5v-kompatibel-mit-ft232rl

When I try to read the flash via Chrome Browser it stops at 100% and doesn't proceed.
Any ideas how to fix this? :/

Thank you very much!

**Comment by henryk86** [comment]
Hi, switch to develop branch and then try another baudrate ( new upcoming feature)

or use another baudrate with the esptool directly.

**Comment by bykof** [comment]
Switching to the `develop` branch and using the baudrate `115200` fixed the problem, thank you very much for this quick help :) <3

**Comment by bykof** [comment]
The baudrate `460800` worked also!

**Comment by Oggymator** [comment]
For 115200 is only working.
