### ISSUE TITLE
Flash process with original file, no Tonies are recognized anymore.

### ISSUE THREAD

**Issue by TobeStar1** [toniebox-reverse-engineering/teddycloud#275]
Hello everyone,

First of all, I would like to express my praise: really great work! I am looking forward to what else is to come. Now, unfortunately, to my concern: 

After I didn't know what to do anymore, I have to contact the professionals. 

Like many others, I watched the Mydealz video and thought, I need that too. After everything worked with the Raspberry and the Docker Teddycloud was also installed without any problems, I was looking forward to the flashing process. 

Everything was connected and read out. It didn't work right away, but updating the Edge browser and reconnecting the USB programmer led to success. 

Thus, I flashed the patched version, and lo and behold, it was done: The Tonibox was recognized, Teddycloud was online, Toniecloud offline. As shown in the video, I checked the boxes, but unfortunately it was still offline. Playing the Tonies still worked, at least for those that were already loaded; however, downloading new Tonies did not work either. In my opinion, there was no connection to the Toniecloud, as also displayed above in the browser. 

I then tried to reconnect to the WLAN because I thought I had entered the wrong WLAN name or password, which also did not work properly. Then I tried to flash the unpatched file again, which worked. But since then nothing works at all anymore. It doesn't recognize any Tonies anymore—nothing at all. 

It starts up fine, but when I place a Toni on it, nothing is recognized. I've already ordered a new Toniebox to rule out that the RFID antenna is defective. Unfortunately without success; it still doesn't work. What was my mistake? How can I still save the box? I still have the files; can I restore it with them as I've already tried? Or do my files have an error…? 

I would appreciate any help you could provide.

Thank you and best regards,
Tobestar1

**Comment by SciLor** [comment]
I would suggest you to open in a thread in our forum, as this is focused on bugs.
Please give more technical details and logs etc. there. You didn't even mention what kind of box you have.
https://forum.revvox.de/latest
