### ISSUE TITLE
Support different base/config directories

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud#33]
| Short | Long | Standard | Description |
| - | - | - | - |
| -d | --datapath | /usr/local/etc/teddyCloud | Configuration data, like config and certs (unix) |

On unix systems, we may start searching in /usr/local/etc/teddyCloud/ for it. If it is missing, we check the path relative to the executable and then the cwd (I or flip the last two, I don't know what's the usual way).

**Comment by pepe82sh** [comment]
> On unix systems, we may start searching in /etc/teddyCloud/ 

Actually it would be /usr/local/etc/teddyCloud

**Comment by SciLor** [comment]
At compile time is a good idea, just setting a compiler-var to override the default set in the Makefile.
The data dir can be set in the configfile itself, so I see no need to override it, if you can override the configfile.

**Comment by pepe82sh** [comment]
> The data dir can be set in the configfile itself

Ah nice, didn't know that! Haven't been looking too hard tbh

**Comment by SciLor** [comment]
[use /usr/local/etc/teddycloud as base dir for data/config/certs if exists.](https://github.com/toniebox-reverse-engineering/teddycloud/commit/729925947bf273b4c2fcc7082176ba98420e391a)
[fix path for symbolic link](https://github.com/toniebox-reverse-engineering/teddycloud/commit/43a8b2306d99a0b2439d848f0b47409ca37fcc9e)

With those commits, /usr/local/etc/teddycloud will be checked for existence and if so the internal (relative) paths will be rerouted to that location.
A cli option is missing, but overriding BASE_PATH can set this path to a custom location.

**Comment by pepe82sh** [comment]
Oh wow, you guys are incredibly fast! I don't think you need /usr/local/etc/.. for the container though. You could either go with what you had or use /etc/, as this seems to be the standard for Linux (don't take my word for it, haven't done much on Linux for some time). I'll go and fork your dev branch. If I come up with something I can sen you a change request.

**Comment by SciLor** [comment]
Just read, that /etc is for mostly for system related thing, so went for /use/local/etc as it was also existing. I may add /etc as an alternative option, for the container it will shorten the path a bit. 

I added it to the container for one reason: have an absolute config path, so you can call the teddyCloud executable not only from /teddycloud

**Comment by pepe82sh** [comment]
Ah yes, I totally agree! Having an absolute Path is exactly what you want.

**Comment by pepe82sh** [comment]
@SciLor is it possible that the workflow for change requests is slightly broken? There seem to be issues that I think are not related to my changes. #108

**Comment by SciLor** [comment]
The workflows don't run until the end, if the user is not allowed to push the docker image. So it fails at this point and cannot do the smoke test. (I currently have solution for that).
But as long as the zip generation workflow is fine (and the docker based workflows are running to this point) this is fine, as the bills itself is working.

**Comment by pepe82sh** [comment]
@SciLor with the current develop branch I'm good to go. My port is installing and running fine, with everything where it should belong. What is your current release cycle? I had to create my own release on my fork, but don't want to use that as a base for the port.

**Comment by pepe82sh** [comment]
And while I'm reading, I think #112 is already the first part of this issue solved 👍

**Comment by pepe82sh** [comment]
Thanks heaps @SciLor ! Now it's just waiting: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276541

**Comment by SciLor** [comment]
done with the enhanced cli
