### ISSUE TITLE
Override noCloud Setting in <UID>.json for figurines

### ISSUE THREAD

**Issue by psour** [toniebox-reverse-engineering/teddycloud#56]
To get some Patches working in conjunction with teddycloud and boxine cloud (blockCheckRemove.310,  noHide.308)
it would be nice to switch an original figurine to nocloud:false even if you removed the password.
It would be a compromise between usable alternative Tags and download of orig. figurines content from boxine.(excl. creative tonies)

**Comment by SciLor** [comment]
This makes no sense to me.
If you have removed the password (so using the blockCheckRemove.310 patch which is buggy) the content cannot be downloaded from the cloud anyway.
The real solution would be to fix the blockCheckRemove patch

**Comment by psour** [comment]
Even if blockCheckRemove is active, teddycloud server will get the the UID from the figurine. No?
Is there more teddycloud needs from the figurine to download content from boxine?
I thought noPass Patch removes the Password, not blockCheckRemove.

**Comment by SciLor** [comment]
I don't mean the tag password, I mean the password for the content.
For accessing the content you need the UID + memory of the tonie, which is used as authentication for downloading the content.

So UID + password (memory)
