### ISSUE TITLE
Show Title in the overview website

### ISSUE THREAD

**Issue by NatroNx** [toniebox-reverse-engineering/teddycloud#58]
In the Content browser currently only the folder and the Date it was created. If I want to reassign a Tonie or check the file of a specific Tonie I need to click through all of them to find it.  

Showing the Title directly in the overview (next to the date) would help in this scenario

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/teddycloud/commit/0e956ca03afde9acc0090ce6d1e60a3e99c6c911
