### ISSUE TITLE
HA Sensors (Autodiscovered) "ContentPicture" and "ContentAudioId" not working

### ISSUE THREAD

**Issue by bluenazgul** [toniebox-reverse-engineering/teddycloud#63]
HA Sensors (Autodiscovered) "ContentPicture" and "ContentAudioId" not working

Issues is present since a while, curenntly running:
TeddyCloud vX.X.X (1b5aa83) - 2023-10-01 18:33:27 +0000 linux-x86_64
running as Docker on Synology DS216+II in macvlan
(same version as Binary only on Ubuntu 22.04 has the same issue)

MQTT Exlporer shows the correct Values for the Entries
![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/171537/e53f8a88-237e-420d-952f-ea7bff9665dd)

Home Assistant sadly shows "Content Audio ID" as 'unknown' 
![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/171537/5a315598-d74c-43ee-8728-284233d4bd00)

and the Image Entity "Content Picture" shows nothing
![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/171537/3a017827-bf5e-43ab-a330-eaa49109642c)

I was able to get this two Sensors working by adding them by hand into the HA configuration.yaml
configuration.yaml:
![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/171537/23b137c6-346b-4442-83cf-a898912d1962)

mqtt.yaml:
![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/171537/a2c79bdd-ef4d-488a-bb83-5ecac2293b7e)

result:
![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/171537/03a2a7a1-3520-4b5e-a3ee-1c699153d072)
On Top you see the Autodiscover Entry for "Content Picture" and on bottom the manuel added mqtt Image Entity

![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/171537/7b5b7f1d-efbb-4754-af2b-f2f73e049f7f)
here the same for "Content Audio ID" (Top: Autodiscovery / Bottom: manuel added Sensor)

here at last the HA Log:
![image](https://github.com/toniebox-reverse-engineering/teddycloud/assets/171537/6353c219-d999-4cea-82ab-b1725b574e47)
`Logger: homeassistant.components.mqtt.discovery
Source: components/mqtt/discovery.py:175
Integration: MQTT (documentation, issues)
First occurred: 08:42:59 (48 occurrences)
Last logged: 08:49:58

Unable to parse JSON LastCloudFreshnessCheckTime: '{"name": "LastCloudFreshnessCheckTime", "uniq_id": "teddyCloud_Box_C8FD19852BFD_LastCloudFreshnessCheckTime", "dev_cla": "timestamp", "avty_t": "teddyCloud/status", "stat_t": "teddyCloud/box/C8FD19852BFD/LastCloudFreshnessCheckTime", "dev": {"name": "teddyCloud Box Beere", "ids": "teddyCloud_Box_C8FD19852BFD", "cu": "http://192.168.178.26", "mf": "tonies", "mdl": "Toniebox", "via_device": "teddyCloud_Server", }}'
Unable to parse JSON LastCloudResetTime: '{"name": "LastCloudResetTime", "uniq_id": "teddyCloud_Box_C8FD19852BFD_LastCloudResetTime", "dev_cla": "timestamp", "avty_t": "teddyCloud/status", "stat_t": "teddyCloud/box/C8FD19852BFD/LastCloudResetTime", "dev": {"name": "teddyCloud Box Beere", "ids": "teddyCloud_Box_C8FD19852BFD", "cu": "http://192.168.178.26", "mf": "tonies", "mdl": "Toniebox", "via_device": "teddyCloud_Server", }}'
Unable to parse JSON ContentAudioId: '{"name": "Content Audio Id", "uniq_id": "teddyCloud_Box_C8FD19852BFD_ContentAudioId", "dev_cla": "timestamp", "avty_t": "teddyCloud/status", "stat_t": "teddyCloud/box/C8FD19852BFD/ContentAudioId", "dev": {"name": "teddyCloud Box Beere", "ids": "teddyCloud_Box_C8FD19852BFD", "cu": "http://192.168.178.26", "mf": "tonies", "mdl": "Toniebox", "via_device": "teddyCloud_Server", }}'
Unable to parse JSON ContentTitle: '{"name": "Content Title", "uniq_id": "teddyCloud_Box_C8FD19852BFD_ContentTitle", "avty_t": "teddyCloud/status", "stat_t": "teddyCloud/box/C8FD19852BFD/ContentTitle", "dev": {"name": "teddyCloud Box Beere", "ids": "teddyCloud_Box_C8FD19852BFD", "cu": "http://192.168.178.26", "mf": "tonies", "mdl": "Toniebox", "via_device": "teddyCloud_Server", }}'
Unable to parse JSON ContentPicture: '{"name": "Content Picture", "uniq_id": "teddyCloud_Box_C8FD19852BFD_ContentPicture", "avty_t": "teddyCloud/status", "url_t": "teddyCloud/box/C8FD19852BFD/ContentPicture", "dev": {"name": "teddyCloud Box Beere", "ids": "teddyCloud_Box_C8FD19852BFD", "cu": "http://192.168.178.26", "mf": "tonies", "mdl": "Toniebox", "via_device": "teddyCloud_Server", }}'`

**Comment by SciLor** [comment]
This partly fixes the problem. AudioID still seems to be broken

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/teddycloud/commit/43ff18e6ade482cc4af6cf0b1c19bd413e35b5df
Should be fixed now
