### ISSUE TITLE
FeatureRequest - Emulate TAG

### ISSUE THREAD

**Issue by marc4s** [toniebox-reverse-engineering/teddycloud#68]
possibility of Teddybench+proxmark3 to emulate an Tag by full UID+HASH

just send the correct cloud request by the entered UID :-)

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/teddycloud/commit/99b9434440fa4ac1e34d98bb32e0ed159802f1db

This shows a download button beside the content.json, if the cloud_ruid and cloud_auth is set and no content file exists.
