### ISSUE TITLE
Enhancement - Library/FileViewer custom length of foldername

### ISSUE THREAD

**Issue by marc4s** [toniebox-reverse-engineering/teddycloud#69]
Enhancement - Library/FileViewer custom length of filename

![Bildschirmfoto vom 2023-11-04 17-43-45](https://github.com/toniebox-reverse-engineering/teddycloud/assets/93420756/2f7d126d-901d-4852-ba3d-5506ab2b10bf)

it is to short if foldername is not used for rUID

**Comment by SciLor** [comment]
Done in /web gui
