### ISSUE TITLE
SEGV - content_json_update_model

### ISSUE THREAD

**Issue by marc4s** [toniebox-reverse-engineering/teddycloud#75]
TeddyCloud vX.X.X (727d387) - 2023-11-07 19:46:31 +0000 linux-x86_64

if someone needs this information ... otherwise you can close this report

`src/contentJson.c:258:33: runtime error: member access within null pointer of type 'struct toniesJson_item_t'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==9==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x55907350af9c bp 0x000000000000 sp 0x7fe2719fc5b0 T2)
==9==The signal is caused by a READ memory access.
==9==Hint: address points to the zero page.
    #0 0x55907350af9c in content_json_update_model src/contentJson.c:258
    #1 0x559073522d5f in getTonieInfo src/handler.c:332
    #2 0x559073534d65 in handleApiFileIndex src/handler_api.c:525
    #3 0x5590736e09b1 in httpConnectionTask src/cyclone/cyclone_tcp/http/http_server.c:546
    #4 0x7fe2758e9ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2)
    #5 0x7fe27597abf3 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x125bf3)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/contentJson.c:258 in content_json_update_model
Thread T2 created by T0 here:
    #0 0x55907345af15 in __interceptor_pthread_create (/usr/local/bin/teddycloud+0x59af15)
    #1 0x55907394c5c3 in osCreateTask src/cyclone/common/os_port_posix.c:87

==9==ABORTING
`

**Comment by SciLor** [comment]
Already fixed in, thank you for your report
https://github.com/toniebox-reverse-engineering/teddycloud/commit/cb157c0de70d20bf78b467a651de7ababf350f07
