### ISSUE TITLE
Setting up teddycloud

### ISSUE THREAD

**Issue by klaushipp** [toniebox-reverse-engineering/teddycloud#80]
Hi,

first of all, what an awesome project!!
I already flashed the custom bootloader and configuration via ngCfg.json seems to work. (Tried waitForPress true/false).
As activeImg I set ofw2 and use altCa plus altUrl in this slot. 
Now I started the teddycloud and copied the client certs into the dir inside of the docker plus the content of the Folder "CONTENT" on the SD card into the data/content/default folder. (I didnt see any 500304E0.json file but just a 500304E0 binary file.).
I set in my dns server the addresses of prod.revvox and rtnl.revvox accordingly and can access the webserver of the teddycloud.
But now when I start to play a bought tonie, the tonie just plays but no information shows up on the webserver.
My question now is, what should I expect? Do I use the setup correctly?

In case my setup works in the end, I would love to offer an easy to follow guide for setup.

Thank you in advance

**Comment by SciLor** [comment]
Hey there,
Great, you managed installing the bootloader on your cc3200 box.
There is no need to copy your box' content to the teddyCloud server. You may do it for convience. Please move the files somewhere, to be sure everything works fine.
If you start your box, and it connects to teddyCloud, it should do a freshnessCheck automatically. You may force it by pressing one ear long after the box is booted. This should create the content.json and the Folders for the content on the box. This should be also visible in the logs.
Did you copy the ca.der generated by teddyCloud as c2.der to the flash of your box?

Please don't use a reverse proxy between teddyCloud and the box, as this filters the client cert authentication.

We welcome any help we can get regarding the documentation to help new users. We just started a central website for that:
https://toniebox-reverse-engineering.github.io/

**Comment by klaushipp** [comment]
I will have a closer look at the c2.der. I copied it once,... But since I rebuilt the teddyCloud container I think the c2.der doesn't fit anymore.
I will test that on the weekend. And come back to you here.
Thank you for your fast reply anyway. :)
