### ISSUE TITLE
Toniebox-ESP32 1.6.C 2022-04-27 Pinout

### ISSUE THREAD

**Issue by jensMF** [toniebox-reverse-engineering/teddycloud#82]
Hi,
I have the PCB version mentioned in the title. I tried to follow these instructions: "Please connect the jumper J100 (Boot) and reset the box to put it into the required mode. Connect your 3.3V UART to J103 (TxD, RxD, GND)." But I realized that the J103 is full of solder and used somehow. Additionally I have a J101 jumper and a J102 pinout for 6 pins. I wonder if this is a new esp32 PCB design? Or are these instructions still correct?

![44564_llcrop](https://github.com/toniebox-reverse-engineering/teddycloud/assets/1620034/633027b7-3204-4cbe-8638-4de16ee4b05e)
![44567_llcrop](https://github.com/toniebox-reverse-engineering/teddycloud/assets/1620034/3086bf10-35e0-42f8-9aa4-3654dcba5c62)

Sorry for the bad picture quality.

**Comment by SciLor** [comment]
There is no new PCB. It is totally identical. You just need J103 and J100. J102 is a JTAG Pin you don't need (and cannot use without blowing an eFUSE). Also J101 is not needed for the flashing process.

The solder on J103 is there because it is unused. You can solder wires onto or a connector (it is the same used for battery/speaker)

![ESP32Toniebox](https://github.com/toniebox-reverse-engineering/teddycloud/assets/1385855/5b61c439-9841-46ee-a62d-2883a87b78a4)

**Comment by jensMF** [comment]
Sorry, I have one more question: What is meant with "Connect to J103 (TxD, RxD, GND)? Should I connect TxD with J103-0, RxD with J103-1 and GND to J103-2 or are J103-0 the TxD and J103-1 the RxD from the ESP32? (counted from the small arrow in the direction it points to, or from the o to the 3)

**Comment by SciLor** [comment]
> Ah, ok. Thank you! I could not find a picture of the ESP32 PCB and the pinout on the website/wiki https://toniebox-reverse-engineering.github.io/docs/wiki/esp32/pinout/ does not cover J102 so I was confused. Did you add the Pins on the J10x pinouts yourself?

Yes, I have soldered them on myself.



> Sorry, I have one more question: What is meant with "Connect to J103 (TxD, RxD, GND)? Should I connect TxD with J103-0, RxD with J103-1 and GND to J103-2 or are J103-0 the TxD and J103-1 the RxD from the ESP32? (counted from the small arrow in the direction it points to, or from the o to the 3)

You'll need to connect the pins to an usb-uart. I strongly recommend you to get into our telegram group https://t.me/toniebox_reverse_engineering

**Comment by jensMF** [comment]
> You'll need to connect the pins to an usb-uart.
Yes, that is very clear to me. I already had a project with an ESP32 where I had to use USB to UART. But, as far as I remember I had to connect the RxD from the USB-UART to the TxD of the ESP32 and vice versa. If that is true, it would be good to know what is what on the board.

Unfortunately I have no Telegram.

**Comment by SciLor** [comment]
The order is from left to right. But you can measure what pin is the GND pin (you should always check that) and if TX/RX are swapped this won't be a problem.
