### ISSUE TITLE
Caching blocks new content from tonies cloud

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud#86]
teddyCloud doesn't redownloads content, if a local file is available due to the caching flag is activated.
So, if the clouds sends new content, the old one should be renamed and the new content should be streamed to the box

**Comment by jensMF** [comment]
As this is a very important issue for me, I wanted to ask what progress is made here. When I manage to build and run my own fork, I would like to look into this issue myself.

**Comment by SciLor** [comment]
fixed with the cache to library and enhanced freshnessCheck
