### ISSUE TITLE
Feature Request: Web interface URL moved to path

### ISSUE THREAD

**Issue by iamthesq** [toniebox-reverse-engineering/teddycloud#90]
Use the root 80/443 ports as strictly communication/api function. Push all web interface/admin functionality to a separate path to allow for auth or nginx rules, limiting access to the system.

**Comment by SciLor** [comment]
Related to https://github.com/toniebox-reverse-engineering/teddycloud/issues/85

**Comment by SciLor** [comment]
I am afraid this won't help. teddyCloud has to terminate the TLS connections to the tomiebox. The certificate is used to identify the box.

Anyway, the toniebox API is already separated from the rest. (V1/V2)
https://github.com/toniebox-reverse-engineering/teddycloud/blob/e04ed1a36371c52cd229bec91d2364633f3ec30d/src/server.c#L59

**Comment by SciLor** [comment]
Can't be fixed
