### ISSUE TITLE
Allow direct pcap export of communication.

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud#91]
Allow direct pcap export of communication.

**Comment by SciLor** [comment]
A workaround may be to use a standard pcap capture tool in the docker container and attach the keys to the resulting pcap file as documented here: https://wiki.wireshark.org/TLS#embedding-decryption-secrets-in-a-pcapng-file

**Comment by henryk86** [comment]
There are some related changes in version after 0.5.1 where you will be able to enable that.
